backend = "full"
palette = "dark16"
check_contrast = true

[templates]
waybar = { src = "waybar-colors.css", dst = "~/.config/waybar/colors.css" }
hypr = { src = "hyprland-colors.conf", dst = "~/.config/hypr/colors.conf" }
kitty = { src = 'colors-kitty.conf', target = '~/.config/kitty/colors-kitty.conf'}
fuzzel = { src = 'colors-fuzzel.ini', target = '~/.config/fuzzel/colors-fuzzel.ini'}
