{
wayland.windowManager.hyprland = {
enable = true;
extraConfig = ''
# Please note not all available settings / options are set here.
# For a full list, see the wiki
#
# autogenerated = 1 # remove this line to remove the warning

# See https://wiki.hyprland.org/Configuring/Monitors/
$MAIN_MONITOR = eDP-1
$EXTERNAL_MONITOR = DP-1

monitor=$MAIN_MONITOR,1920x1080@120,0x0,1.0
monitor=$EXTERNAL_MONITOR,2560x1440@60,1920x0,1.0, transform, 1
monitor=,preferred,auto,auto

# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# Execute your favorite apps at launch
exec-once = bash ~/.config/waybar/start.sh
exec-once = mako
exec-once= [workspace 1 silent] firefox
exec-once = sleep 1 & swww init & swww img ~/wallpapers/one-piece-nika-moon.jpg & 


# bind 5 workspaces to each monitor
# need to think if this is something I really want
workspace = 1,monitor:$MAIN_MONITOR
workspace = 2,monitor:$MAIN_MONITOR
workspace = 3,monitor:$MAIN_MONITOR
workspace = 4,monitor:$MAIN_MONITOR
workspace = 5,monitor:$MAIN_MONITOR

workspace = 6,monitor:$EXTERNAL_MONITOR
workspace = 7,monitor:$EXTERNAL_MONITOR
workspace = 8,monitor:$EXTERNAL_MONITOR
workspace = 9,monitor:$EXTERNAL_MONITOR
workspace = 10,monitor:$EXTERNAL_MONITOR

# Some default env vars.
env = XCURSOR_SIZE,24

# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
input {
    kb_layout = it
    kb_variant =
    kb_model =
    kb_options = caps:swapescape
    kb_rules =

    follow_mouse = 1

    touchpad {
        natural_scroll = true
    }

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    repeat_rate = 70
    repeat_delay = 150
    natural_scroll = false,
    float_switch_override_focus = 2
}

general {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    gaps_in = 2
    gaps_out = 4
    border_size = 1
    col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
    col.inactive_border = rgba(595959aa)

    layout = master

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
    resize_on_border = true
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    # round corners of window
    rounding = 10
    
    # blurs background
    blur {
        enabled = true
	# how much to blur
        size = 3
	# how many passes of blurring
	# don't let this value be too high -> less snappy
        passes = 1

	# floating windows ignore tiled windows in blur
	# reduce overhead on floating blurs a lot
	xray = true
    }

    # minimal effect -> I prefer snappy
    drop_shadow = false

    # shadow_range = 20
    # shadow_render_power = 3
    # col.shadow = rgba(1a1a1aee)

    # give window transparent effect
    # do this for both active, inactive, and full screen windows
    active_opacity = 1.0
    inactive_opacity = 1.0
    # dont change this, otherwise whenever you fullscreen youtube video 
    # you will see the background. Unfortunately, hyprland doesnt allow 
    # overriding this using window rules.
    fullscreen_opacity = 1.0

    # how much to dim rest of screen when special workspace is open
    dim_special = 0.2


}

# override only for kitty 
windowrulev2 = opacity 0.75 override 0.75 override,class: kitty
# resize floating firefox popups
windowrulev2 = size 800 360,class: firefox, floating: 1
# center firefox floating popups
windowrulev2 = center (1),class: firefox, floating: 1

animations {
    enabled = yes

    # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    animation = border, 1, 10, default
    animation = borderangle, 1, 8, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

dwindle {
    # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = yes # you probably want this
}

master {
    # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
    new_is_master = false
    mfact=0.55
    new_on_top = false
    orientation = left
    always_center_master = false
    inherit_fullscreen = true
}

misc {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more
    force_default_wallpaper = 0 # Set to 0 to disable the anime mascot wallpapers
    new_window_takes_over_fullscreen = 2
}


# to define keybindings for a group (i.e. to enter a "resize" mode)
# will switch to a submap called resize
# bind=ALT,R,submap,resize

# will start a submap called "resize"
# submap=resize

# sets repeatable binds for resizing the active window
# binde=,right,resizeactive,10 0
# binde=,left,resizeactive,-10 0
# binde=,up,resizeactive,0 -10
# binde=,down,resizeactive,0 10

# use reset to go back to the global submap
# bind=,escape,submap,reset 

# will reset the submap, meaning end the current one and return to the global one
# submap=reset

# keybinds further down will be global again...
# WARNING: be sure to define a bind to exit this mode. You can also define the keybind to 
# to first resize and then exit (look below for chained binds)


# See https://wiki.hyprland.org/Configuring/Keywords/ for more
$mainMod = SUPER

bind = $mainMod, RETURN, exec, kitty
bind = $mainMod, Q, killactive, 
bind = $mainMod, B, exec, firefox
bind = $mainMod, R, exec, rofi -show drun -show-icons

bind = $mainMod, F, fullscreen, 1
bind = $mainMod, T, togglefloating, active
bind = $mainMod, T, centerwindow,
bind = $mainMod, M, focuscurrentorlast,

bind = $mainMod, G, togglegroup,
bind = $mainMod, N, changegroupactive, f
bind = $mainMod SHIFT, N, changegroupactive, b
# move windows out or into groups in specific directions
bind = $mainMod SHIFT, H, movewindoworgroup, l
bind = $mainMod SHIFT, J, movewindoworgroup, d
bind = $mainMod SHIFT, K, movewindoworgroup, u
bind = $mainMod SHIFT, L, movewindoworgroup, r

bind = $mainMod, S, togglespecialworkspace, scratch
bind = $mainMod SHIFT, S, movetoworkspacesilent, special:scratch

bind = $mainMod, W, exec, bash ~/.config/myoldwaybar/start.sh
bind = $mainMod, W, exec, swww init & swww img ~/wallpapers/one-piece-nika-moon.jpg & 

bind = $mainMod SHIFT, R, exec, ~/.config/hypr/rotate_monitor.sh


# Move focus with mainMod + arrow keys
bind = $mainMod, H, movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# Switch workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move active window to workspace
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9


#list of env options hyprland advices to use for nvidia
env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = WLR_NO_HARDWARE_CURSORS,1
# these two options make firefox crash when using something like telegram web
# env = GBM_BACKEND,nvidia-drm
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
'';
};

}
